### ISSUE TITLE
Fix Socials

### ISSUE THREAD

**Issue by bitcoinbrisbane** [block52/website#10]
Remove the "Get Support" heading and all the items below
Change the "Get Us" to "Socials"
Remove Facebook and add

- Link to GitHub
- Link to Twitter
- Link to Telegram
- Link to ProtoMail and its PGP pub key

@Dzeezbtc setup a Telegram channel for the community

**Comment by Dzeezbtc** [comment]
Telegram community page
https://t.me/joinchat/onG3S1jQ7TY4ZGE9

Twitter
https://twitter.com/BLOCK__52?s=03
